version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean package
      - run:
          name: Unit Tests
          command: mvn -Dtest="dw.servico.**" test

  integration-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean package
      - run:
          name: Integration Tests
          command: mvn -Dtest="dw.integracaoTestes.**" test
          timeout: 100000

  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a datawarriors-back web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a datawarriors-back web

workflows:
  integration-test:
    jobs:
      - integration-test:
          filters:
            branches:
              only: feature/SPC-46

  build-test: 
    jobs:
      - build-and-test:
          filters:
                  branches:
                    ignore: main
  build-deploy:
    jobs:
      - build-deploy:
          filters:
                branches:
                  only: main